version: "3.8"
services:
  redis:
    image: "redis:alpine"
    networks:
      - backend

  db:
    image: "postgres:13-alpine"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - backend
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 3
  
  vote:
    build: ./vote
    ports:
      - "3000:80"
    networks:
      - backend
    depends_on:
      - redis
      
  worker:
    build: ./worker
    networks:
      - backend
    depends_on:
      - redis

  result:
    build: ./result
    ports:
      - "3001:80"
    networks:
      - backend
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: postgres

networks:
  backend:

volumes:
  db-data:
